import logo from './logo.svg';
import './App.css';
import {useState, useEffect} from 'react';

function Sequence(){
  const sequence = "GTCCTAATGACAGTTACCTCTCGCGGGTCAATTTTAAATTGGAGCCTTTCACAAGGATGTATGTAAAGGTTCGGAATCGGGGTTGCGTGACATACACCAAGAGGCTCGAGGCCAGTACATTATGCAATGGCCCACTACGATTGTTTTGATCTGGGAACAGACCAAGTTGGTAGCTGTATATCCCCACGTCTTGAAACTAGATGTGCCCTCGTCGTCAGAAACTCTGATTCACAGCCTATCCCGATGAGCGTCAGTTTGCAGTAGGAACTGGCCGTGGTGAGCATGTTAAAAGTACGCGGCGTGAACAAAGTAGATTCGGGGGAGACTTTGCTAGATTACGAGGCAATAGTTACACTGGGTGGCCACTTCTGCGCCTCGTTTAACAAATGCGGAGGGTCGCCTTCCCTATCGGTCGTGCGACACGCTTAGCCTATCTATAGTGCATACAAAACATAAATGCCTCTATCACCCGTGAAGATGTGCCGCTGCTATTAGCTGGCAAAATGAGGTGAATCTATTACTAGGTATCTCAGTCGGAACATCCTCGTCTTTGTCCCTTTAATAAACCGCATCCGGGACAAATCTCATCACGATGCCGCCCAGGATTCTTGTAGTACCGGCAGATGACTGCGAGCATGCATTTCCGTAGTCAGTCTCCTCGCTCGCCGTGGGTCGGCATAATTGCCCTCTCAAAGCTCCAGATGATGCCATTCGAAGCGAGGTATAGAGAAGCACTGTACGATCTACGCAGCAACCAATGGTAGTGTGCCACAAACATATGAGTTTGCTACTGCGGGTCGGATGCCACATTAAACGTGGTTACCCTTTAATGACCGATCCGAACTCCCTGTCCATGGTGCGAAGGACGTACCTACACGTCTCTGCTCGGGATCCGGCCCCCGTTTGTTGCCCAAGATTGCTCGAGAACATATGTGCCGTCGTGTCTAGAAAGATACAGAGTGAGGACCTCGTCGGATAACTTATGACAAGGACCGTTGATCAGAGTAAGCGCCCGCAGTCAATTTCTAACTTGAACAACGTTGAGTATCAGGTACCCGAGAGGGGCAGCGCTTCATGGGAATACCGCTTGTCGTGTACACAACACTCGACGGTTAACCCTTCGGAAATCGGTCTTTGCCTGGGGCACCAACGACATTTAGTGAACTAGATGAGACCAGTCAGCTCTATTCAGAGACGGTCTTGAAATTAAGCCGTCAATAATGACTAGTTCGGCGGGGGTGGCGCGTCTGCACCAGGTCGAAATGTGTGTGCAGGTACAAGCTCCGACTACAACTTTCGATCTGGATATATGGGGTCCCCGAGGTTGGTTCAGCGGGTCCAAGTGATGAGAACGCTGGACCGCCAGACATACGATTTTATTTTTCGATTTAATCGAAGGAGTCGCGGCCGTGCGAAAGAAAGGTGTTAAGTAACTCTGTGAAACTATTTCTCGAGGATTGCCACTGGGTAAACCACGTTGCGCGCATTACAAGAAGTCCCGGTCCAGATCTAGGACTCGGCCACAAAAACATTCAAAGCGGCACACACAGAGCTGACCAGTGCGACCAAGATGAGATGAACTTCGGTAACGCCGACTAATATTCTCGCATATTCCACTGAGAAATCCAAGTCATATTCTGCAGTCGTTCGGCGCATCGGATGGCGTCCTCCGAATAAAAGTTTGTCATATGGATCAAAGAATCTTTTATGGCCGTCAGATGTAAGTATCCATTCCTATATCCAACAAGTTCGCCTCAATAGATACCGGTGGTAGCCGATTACCGCTACGCTATGGTGCTGCTTCAACGGAAAAGGGGGTTCCGGCCGCGTATACGTGAGTCGGGTTAAGGGAGGTGGCAGGCTAATTAACTATAGCAAATGTGGTTTGCCGTGGGGTAACTATCGATGCTTAATCTAAACCTTTGGTGACCTGCTGTGCGCAATGTCACCGGGTAAGATTGGCCAGATGCATATTTAACGGCCGGGAGAGATGAGTCAACCCCGCGAACAGTCCCTGCTAATGTATCCAGGCGTGAGTAGTTCAGGGTCGATGGCCCATATACTGCGAGGCGTCGGCTGGATCTGTCTGTTCGGGAGCCTATGCAGCAGCATGGATCCCGCGTCACTAATTGTGTCGTATGTTATTATATGTGAACCTGCACCTTTTGACTTCTCAGGCACTCCAATCGTGAAGCGAAACCAAACCTCGGGAGGCGTTAATTGTCCGACCATCCGCGAATGTAGATTCCAATACGAGGCTGGGCAAATATACCATAGCCGCAGGTAGGACCCAGAGATTCCGGGGCTACATTTCGGAAACTGTGCTCGAGTCTAAGCTGCGTTGTGGCTCCAGCGACCCAGGGAAAGTATGCCTAACACAGGCACCAAGTTCCACCCTTCCCGGCATTATCCCCGCCACCCTCTGCACCGCACGTAAACCAGTTCGGTACTACACCCGCGTGTAATTAATTATGCAGGTTAATTAGCGCATTCGCACCATTTAACGTTTTTCCGGAGGGAATGATGGCAGCTGTCTACGAACAATGACTTGGCTGGCAAGCGGACATGGCCCAGTGCAAGAATGACCCTACAGGATTCTCCTCCATGAGGCGACCTTACTCTTGCAGTTCGTCGACCATGCAGACCTTAGTCCGGCCGGTCGGAAGACGAGCTTATTTGCGAAGGCGAACAGAGCGCGAAGTTGTGCTGGACCGCCCGGACATGAAGGAGGGCGGACTATTTGACTAGACACACAAAAGCATATTAGAGATCAAAAAGTCTCAAATCACACAGCACGCGCCACCGTCAATATTCCCCCGGAGGCGTGGTGACCCCAGTCCGCATTATTGTTGGACGTCCAGCAGCCTCTGTCCTTGATATTCCGCGGCTCTTTAAACCAACTTACTCGGGTCTTTCCTAGCTTGACGTGCCTGCTCTTAACCTGCATTACCTTGCCGCTGGGTTCTATTGTCGTATATCGATATTACAATAAAAAAGTTATGTCTTTCTAGACGGGCTACCTAGTACGGCGAACGTAGTATCATTCTTAGCAGTCCTGCGGCTTTTAATAGGCACTTTAACCCGCCAAGATGGATAGCAATTAATTTCAATGCAGGCCGGGCAACCTTAAGAGTTAGTTTTGCACAAAGCAACTAGCCGCTAAAGTTGAATTCGTTCACCAAGATCCAGAAATCACCAAAGGGTTGACTAGCTGGCTTTATCTCTATCGCAAACAGCCCCTATTACAACGGGAGTGTTAGTACGAAGGAGGATTGCCAACTATTTTTGTTGACCAATGGCGACAACCGGAGCCTCGTCCCAAAATATTACCGACACAAGCACGCCAATTAATGCGCGGGGCACCATTAGTTTAAATTGTTTTTTCGTGAGCTGCGGAAAGTTATTTTGCTCCGCCATAAATTTTCGCTTGCTCGGTTTTCGCCAGGCCTGTTGTATTACTACTGCTTACCTTATTGGCCCAGATACTTCCCCAGAATGTGCTTCAATCGCCTTCCCAGTATACGCAAGGGAGGTGTGACCGGGACTAGATCACGTCGATGAAAGGATCACTCCACGCGCCAGCGTACATACGAAGTGATGCTGAACATGGAATCTCGTAGACGGCTCGCGGACAAATCGACCCTGCGCTGTGACGCTGTTAAAGCCATGGCATTTGCAAGGGCCAAGAGGATCTGGATACTTATAGCAGCAGTCGTCTAGTGCAATGAACGTCGTAACTAACTTACGGCTCCGCCTGGGTCACGTAAGATCCAAAATAAGCAGGCTCAGAGGGGTGCGTAAGCAGGGTACTTTTCGAGTGTGTTCAGATCTACCGGCTTGTCAAAATGTCTAAAAGAACTAACACTCCACTCAGATCCGCTGGAAAGTCGTTCTAGAATCGGGACCCTAATCAACTGTCCACGCTATAATCGCTGTGTCTGAAAAACATAAATCTCTTGCGGAAGTAGCTATCCCAATCTCCGAATGTTAGGGTCCACTATCATCGAGCAAATGCTCGAAACACAAGTATTTGTATAATTAGTTACCACTTCTAGACAAAGCCCTGCACACCTCAACATGCCGGCTCCCTGCGGGCGAGCAACCGGAGCGGAACCCGCTTTTAGGCGATAATTTGGGCGAGTTTTGCACAAGATTGGCTGTTTGGTAGCGTCCGACACAAGTAACGTCGCGCATAACGTACACGCCGGAGCTTGTCCATTCAAGCCGGAGGTCCCGGATTCAGAAGGGATCACTCTGATGTCCTAAAAGCTTGTGTTTCGCGAACGGGCTCCAGGCATAAGCCCCTCAGGCCGAACTGAGAAGTTAACTCCGTGTCCATTCCAAACTCCTGCACGTCTTTTAAACTTGGTAGCACATGTTATTGTGACGGTACCGTTTCCCGCTGAAATCCGACTTATCTAAGTTGGAATGTCCACGCATCAGCGTGTCAACCAGAAACATGAGACGTTCACAGTAGTGGACTCTCACCGCTCACCTGTCTAATCGCGGGCTCTCTTTCCGTGCGGAGGATAAGGCTAATGATTCTCTTACTCACGTAATGCGACGAAGCGTCTTAGCGAGCGACGCTCTTGTTGTAGAAATTGGGTGGGATTGAGAGGGCATTCGACTCGGATGTTTGCAGACAACGGTCCAAAGGATGCTTTAGCGAATCACGATGTTTTGAAATAATTCGCACTACCTGAATGTACACTATAAGGAAGTCACTGGACTGGCGCCTGATGTATTTAATGGAGATTTCCCCGACTGCGGAACGGTGTTTCGCAGTGGAGTGCTTCTAGGGCTAAGATTGGCCCCGTACTATTTTGAAACAACCCTAAGAAGACATGATTTCCTATGTGTGCTGCCTGAGATGTTAATAAACCGGGAAGGGATGCGGTAAACATGGCCGACGGCACCTTCTCAAGGGCTGCGGGTCTCGATTCAAAAAGGACGTGGACTCAGTGCGGGTACATGCGGGCGGCAGCCAACCTACTACCCCAGCCTTCCGAGCTTCTCGGATCGTCCTGCAAGGGGTCCCACATCCGGCAGGGCGGAGAAGCTGCAAGCCTGTGCACACTTTCCCATGATTTCATAGCGACTTGGACAAGTCAATCCCGAATTCTGTCAGGACTTACCTAATAGCCTTTCCATCCCACCGTTCGAATTCTTTGAATAAAACAGCATGTTGACCGGTTGTTGAGCCGAACGTCCAGTTTTTATTCTCCAAGCCATCACAAAACTCGCAGGGCCAGCCTGGTACATCTTTCAACGAGCTTCACGATCTATCCGTGATTCTATTCCACCCGGGTTACGAATACCGGGATGGGTCGTGCGTCCCACAATAGTCCGCTTCGAGGGGGAGCCGTCCTACAATCACAACGGCCAAGGTCATCCTGGTTCGCCGCGCTCGTACCCCCCTCGGACAATGAATGCACACAGGGAACCCGGGTTGTCTCAGAGCCTCGACATCATCACTCTATGGCCGTGAAATAAAGATTCTGCACAGCCTTCGCTCGGCGTAGTCAACTTACTGTAAACGGGCTTGTGAATGTACCACTCGGAAAACGAGCAATAAAAGGTATTCGCAAGAATGACGTGGAAGATTTACAAAACTCGGGAATGGGTAGGCAGTGTGACGCTGCAGTTAGCAACAATTGGTCTGCACCCCTATGAGGTGGGACGGGGCAACCTAAAGGTGAACGTCAGGTCGTTTCGAGATTGCGTAGATCACAATGCTAAGTCCGGACATGTTGTCACCGCCTATGTTTAGGACCGTCGGATATAGGATCGATGAGCAAGGTGGCTCTCTATGACCCATTCAATAACAATCGCGCCTAGCGTGTGTATGAGAACAATATTCAGCATCGTGATGTGTTATTATCTAAGTACTGGCGACGGCAGCTATGGAGGTCCAGTTTGAGAGGATAAACTTGGTTCAGGCTCCTCTGGAACCTCGCAGCTCCCTCTTTTCGACTGGCGGTGATTCTAAGAAGACGACCCATCGATGCTTTTGGTACACTGCCTCCGTTTTCCCAGGCCAGCGCAGTTAACGATCGGAACGACCCAAAGCGATTAACAAAAACAAAGCAATCGTGGGTCAACACCGCTGGCATAACACGCTTGGGATACTAACGCGGCTGCCCTTTGTTCCTTTACTGTATAAGAGTGTAATATAACCCGATTCGAAACAGGCCAATAGAGACCTGTTTAGGGCTTCATGGACGCGTGGGACGATGAGAAGGCCTGTTCAGCATGACGTAATTGCCCCGCTCCTTCACTAAAGTTTAGAAAGCGGCAGGGACGGTTCAGAAACCGCTAATCCAGACTAAGTTTCTTGGTGAGGGGAGATCCAGCTTCGACCCGAGTTTTTAAAGTGATACACGGGGTTTAGGCGCGCCTAGCCCGTGGGAACCCTATTATAGTGTTCTATGGTATCAAAAAGCTGTGGAACATATATAGCCTCTGGGCTAACCCCCCAATTTTAGTAGTAGTGCTGAAGTCTCGCGCTGTTCACACCAATCCGGAGAAACTCGCAATATTTGATTGACCAATCCCATCATCCATCTTGTTACTGGTGAGACGAATGAAATCTGCTAGCCGGAGAACGCGAGCTCAGGTGTACTGGGCAGTGACTTTAGCCTGTAGGTATTCACACTTTTTACTTATGGAGTATCAGGTCCCGGTGGGCGTCTGGGTGAGTGTTGGCAACATTAAGTGTGAGGGAAGTGTACCCATCCTCGCGAACCATTTGCGCTTGGGGTACATTGTTGATCCGAG";
  const sequenceName = "DNASequence1";
  const [select, setSelect] = useState(-1);
  const [nucleotides, setNucleotides] = useState("");
  //Segment Splits
  const splits = [700,1500,2330,3000,4000,5100,6000,6777];
  const scores = Array(splits.length).fill(123);
  //Calculate segment indices
  let prev = 0;
  const segments = []
  const lengths = [];
  for(let i = 0; i < splits.length; i++){
    const segment = [];
    segment.push(prev+1, splits[i]);
    segments.push(segment);
    lengths.push(splits[i]-prev);
    prev = splits[i];
  }

  //const[segLengths, setSegLengths] = useState(lengths);

  const segmentBoxes = lengths.map((length,idx)=>{
    const styling = {height: `40px`, width: `${length/10}px`, background: select==idx?"#CCCCCC":"#888888", display: "inline-block", boxSizing: "border-box", border: "1px solid #000000"};
    return <div style = {styling} onClick={() => {
      if(select !== idx){
        setSelect(idx);
      }else{
        setSelect(-1);
      }
    }}>{idx+1}</div>
  });

  useEffect(()=>{
    if(nucleotides !==""){
      if(select<0){
        setNucleotides(sequence);
      }else{
        setNucleotides(sequence.substring(select ===0?0:splits[select-1],splits[select]));
      }
    }
  },[select]);

  return(
    <>
      <div style = {{textAlign: "center", width: "100%"}}>
        <div>
          {select<0?`Total Length: ${splits[splits.length-1]}`:`Segment ${select+1}`}
        </div>
        {segmentBoxes}
        <div>
          {select<0?sequenceName:`Nucleotides: (${segments[select][0]}, ${segments[select][1]}), Score: ${scores[select]}, Length: ${lengths[select]}`}
        </div>
        <button onClick = {() =>{
          if(nucleotides === ""){
            if(select<0){
              setNucleotides(sequence);
            }else{
              setNucleotides(sequence.substring(select ===0?0:splits[select-1],splits[select]));
            }
          }else{
            setNucleotides("");
          }
        }}>
          {nucleotides===""?"Show Nucleotides":"Hide Nucleotides"}
        </button>
        <p style = {{whiteSpace: "normal", wordBreak: "break-all", width: "80%", marginLeft: "auto", marginRight:"auto"}}>{nucleotides}</p>
      </div>

    </>
  );
}


function App() {
  return (
    <div className="App">
      <Sequence/>
    </div>
  );
}

export default App;
